### ISSUE TITLE
Can't compile unittest target with automem in dependencies

### ISSUE THREAD

**Issue by crimaniak** [atilaneves/automem#11]
After adding automem 0.0.9 to dub dependencies my -unittest build failed with error message:

../../.dub/packages/automem-0.0.9/automem/source/automem/ref_counted.d(9,12): Error: module test_allocator is in file 'test_allocator.d' which cannot be read
import path[0] = source/
import path[1] = ../../.dub/packages/automem-0.0.9/automem/source/
import path[2] = ../diet-ng/source/
import path[3] = ../../.dub/packages/mysql-native-1.1.0/mysql-native/source/
....

**Comment by atilaneves** [comment]
I can't reproduce this with dub. Are you using a custom build system?

**Comment by crimaniak** [comment]
No, I have standard dub vibe.d project and this problem appear after adding automem to dependencies. My dub.json file:
```
{
	"authors": [
		"Alexey Kulentsov"
	],
	"name": "virtual-cm",
	"license": "proprietary",
	"copyright": "Copyright © 2016, Alexey Kulentsov",
	"description": "Web-based Virtual CloudMaster",
	"dependencies": {
		"diet-ng": {"path": "../diet-ng"},
		"vibe-d": "~>0.7.29",
		"vibe-mqtt": "~>0.1.6",
		"mysql-native": "~>1.1.0",
		"pegged": "~>0.3.2",
		"automem": "~>0.0.9"
	},
	"sourceFiles": [
		"scramble.o"
	],
	"versions": [
		"VibeDefaultMain"
	],
	"stringImportPaths" : [
		".",
		"views/",
		"source/"
	]
}
```
The only non-standard thing here is custom version of diet-ng.
I notice test_allocator and unit_threaded are dependencies of automem, they are downloaded by dub, but paths are not added when I run `dub build -b unittest` of my project. Full error message:

Performing "unittest" build using dmd for x86_64.
automem 0.0.9: target for configuration "library" is up to date.
diet-ng 1.1.4+commit.6.g7079828: target for configuration "library" is up to date.
vibe-d:utils 0.7.31: target for configuration "library" is up to date.
vibe-d:data 0.7.31: target for configuration "library" is up to date.
vibe-d:core 0.7.31: target for configuration "libevent" is up to date.
mysql-native 1.1.0: target for configuration "library" is up to date.
pegged 0.3.3: target for configuration "library" is up to date.
vibe-d:http 0.7.31: target for configuration "library" is up to date.
vibe-d:diet 0.7.31: target for configuration "library" is up to date.
vibe-d:mail 0.7.31: target for configuration "library" is up to date.
vibe-d:mongodb 0.7.31: target for configuration "library" is up to date.
vibe-d:redis 0.7.31: target for configuration "library" is up to date.
vibe-d:web 0.7.31: target for configuration "library" is up to date.
vibe-d 0.7.31: target for configuration "libevent" is up to date.
vibe-mqtt 0.1.8: target for configuration "vibed" is up to date.
virtual-cm ~develop: building configuration "application"...
../../.dub/packages/automem-0.0.9/automem/source/automem/ref_counted.d(9,12): Error: module test_allocator is in file 'test_allocator.d' which cannot be read
import path[0] = source/
import path[1] = ../../.dub/packages/automem-0.0.9/automem/source/
import path[2] = ../diet-ng/source/
import path[3] = ../../.dub/packages/mysql-native-1.1.0/mysql-native/source/
import path[4] = ../../.dub/packages/vibe-d-0.7.31/vibe-d/source/
import path[5] = ../../.dub/packages/libevent-2.0.2_2.0.16/libevent
import path[6] = ../../.dub/packages/openssl-1.1.5_1.0.1g/openssl
import path[7] = ../../.dub/packages/pegged-0.3.3/pegged
import path[8] = ../../.dub/packages/vibe-mqtt-0.1.8/vibe-mqtt/source/
import path[9] = /usr/include/dmd/phobos
import path[10] = /usr/include/dmd/druntime/import
dmd failed with exit code 1.

After adding these dependencies to dub.json problem was resolved, but I expected dub have to resolve dependencies itself. Is this problem of package, dub or my wrong expectations?

**Comment by atilaneves** [comment]
I still can't reproduce this. I copied your `dub.json`, deleted the lines about diet-ng and `scramble.o`, added an empty `source/app.d` and `mkdir`ed a views directory. Compiled and linked fine.

**Comment by crimaniak** [comment]
I make some experiments but can't reproduce it too in the clean project, so I will close it.
