### ISSUE TITLE
Invariant violation in debug mode

### ISSUE THREAD

**Issue by drug007** [atilaneves/automem#43]
```D
/+dub.sdl:
dependency "automem" version="~>0.6.1"
+/
import automem;

StringM str;

void main() @nogc
{
	str ~= "a";
	str.popBack;
	str ~= "a"; // generates the error "Assigning to non default initialised non mutable member" in vector.d:297

	assert(str.length == 1);
	assert(str[0] == 'a');
}
```
due to the fact that after `popBack` call and adding new element again the last element of the storage has already been initialized so the check fails.

**Comment by atilaneves** [comment]
Why do you think this is an issue? `StringM` is an alias for `Vector!(immutable char, Mallocator)`. Which means that the individual elements are immutable. If allocating storage and immediately populating the elements, this is ok - they can be immutable after that. But what you have there is:

```d
    str ~= "a";  // ok
    str.popBack;  // ok up until to here
    str ~= "a";  // oops, just modified what should have been an immutable value
```

The workaround is to use a mutable char vector instead, `Vector!(char, Mallocator)` instead.

**Comment by drug007** [comment]
"...non mutable member" - OMG. Sorry for noise, I was in a hurry yesterday.
