### ISSUE TITLE
@nogc support for classes

### ISSUE THREAD

**Issue by vittorioromeo** [atilaneves/automem#5]
Currently, this code snippet below does not compile:

```d
import automem;

class Foo
{
    this() @nogc
    {
    }

    ~this() @nogc
    {
    }
}

void main() @nogc
{
    auto x = Unique!Foo();
}
```

> Error: @nogc function 'D main' cannot call non-@nogc destructor 'automem.unique.Unique!(Foo, IAllocator).Unique.~this'

Would it be possible to have the code above compile? It would be great! 

Ali has a nice trick here that shows how to make the compiler assume something is `@nogc`:
https://forum.dlang.org/post/oat6lu$n94$1@digitalmars.com

**Comment by vittorioromeo** [comment]
This is also a great resource:
https://www.auburnsounds.com/blog/2016-11-10_Running-D-without-its-runtime.html

**Comment by atilaneves** [comment]
This is really a [druntime bug](https://issues.dlang.org/show_bug.cgi?id=17297) but I guess you know that given the link you posted. I wasn't aware of using alternatives to `destroy` to get around the issue. I'll look into this. Fortunately, since it's D I can use a `static if` to call `destroy` for everything _except_ classes.

**Comment by vittorioromeo** [comment]
> Fortunately, since it's D I can use a `static if` to call `destroy` for everything except classes.

That unfortunately means that classes cannot be used for C++-style RAII with Unique/Shared ptrs though, as the destructor won't be called... right?

**Comment by atilaneves** [comment]
Not at all, the destructor will definitely be called. Check the unit test accompanying the fix.

I ended up calling my custom destroy in all cases, it was easier that way.
