### ISSUE TITLE
RefCounted fails to destroy payload in combination with zip

### ISSUE THREAD

**Issue by fyfrey** [atilaneves/automem#56]
RefCounted seems to have issues when used together with `zip`: The refcounted payload is not destroyed. I stumpled upon this when using valgrind to check why my program was not freeing its memory. It works fine with `lockstep`.
Below is a short reproduction of the error. Runnable version: https://run.dlang.io/is/eVIP3r 

```d
/+dub.sdl:
dependency "automem" version="~>0.6.4"
+/
import automem.ref_counted;
import std.range;
import std.stdio;

int created, destroyed;

void main() {
    {
        RefCounted!S s = RefCounted!S(1);
        auto r1 = repeat(s, 2);
        auto r2 = repeat(s, 2);
        foreach(s1, s2; lockstep(r1, r2))
            assert(s1.val == s2.val);
    }
    writeln("after lockstep: created ", created, " vs destroyed ", destroyed);
    assert(created == 1);
    assert(destroyed == 1);
    {
        RefCounted!S s = RefCounted!S(1);
        auto r1 = repeat(s, 2);
        auto r2 = repeat(s, 2);
        foreach(s1, s2; zip(r1, r2))
            assert(s1.val == s2.val);
    }
    writeln("after zip: created ", created, " vs destroyed ", destroyed);
    assert(created == 2);
    assert(destroyed == 2); // fails!
}

struct S {
    @disable this();
    @disable this(this);
    this(int val) {
        this.val = val;
        created++;
    }
    ~this() {
        destroyed++;
    }
    int val;
}
```

Thanks for looking into this!

**Comment by atilaneves** [comment]
I wrote a test for it and as far as I can tell zip makes lots more copies and doesn't drop the ref count to 0. Might be a problem with zip.

**Comment by submada** [comment]
It is bug in compiler, if foreach expand rvalue tuple, then destructors for expanded elements are not called.

Example:
`foreach(s1, s2; zip(r1, r2)){}   //destructors for s1 and s2 are not called.`


`foreach(s; zip(r1, r2)){}   //this will work OK.`

**Comment by atilaneves** [comment]
> It is bug in compiler, if foreach expand rvalue tuple, then destructors for expanded elements are not called.
> 
> Example:
> `foreach(s1, s2; zip(r1, r2)){} //destructors for s1 and s2 are not called.`
> 
> `foreach(s; zip(r1, r2)){} //this will work OK.`

Is there a bug filed for this already?

**Comment by submada** [comment]
https://issues.dlang.org/show_bug.cgi?id=21626
